### ISSUE TITLE
Jenkins does not find Unity installation

### ISSUE THREAD

**Issue by DaNeubi** [jenkinsci/unity3d-plugin#16]
Jenkins Version 2.150.1 does not find Unity 2018.3.0b3 as Installation.

**Comment by ariessanchezsulit** [comment]
@DaNeubi Were you able to fix this? I'm also getting the wrong `/Editor/Unity` suffix on mac os.

**Comment by KieranBond** [comment]
@DaNeubi @ariessanchezsulit if you can show me how you've got it configured I might be able to help. I was having a similar issue and seemed to get around it

**Comment by DaNeubi** [comment]
Not using Jenkins currently. Will close this Issue. Would not be able to recreate the error I guess.

**Comment by ariessanchezsulit** [comment]
@KieranBond I know this one is a bit late, but if you're curious to find out the cause of my issue, here are the details. but I'm thinking, probably the docker linux environment is the one causing the problem.

> Docker installed on a Windows 10 pro machine (running on linux environment)
> Jenkins installation using docker
> Normal setup of unity3d-plugin (with windows path setup)
