### ISSUE TITLE
error when trying to build on jenkins with unity 3d plugin

### ISSUE THREAD

**Issue by HristoKehayov** [jenkinsci/unity3d-plugin#21]
ive been getting this error message -> 
Scripts have compiler errors.

(Filename: /Users/builduser/buildslave/unity/build/Runtime/Utilities/Argv.cpp Line: 306)

Aborting batchmode due to failure: Scripts have compiler errors.

ive checked everying and dont know what to do anymore. my scrips have no errors
ive tried build it from editor itself without errors so why doesnt work on jenkins ....
i will be very happy if someone has a solution on that case. Thanks in advance!

**Comment by JamesMorDigi** [comment]
@HristoKehayov How did you resolve the problem ?

**Comment by HristoKehayov** [comment]
Sorry i don't remember anymore. I was also using Ubuntu os. What I remember is that i changed the default jenkins user to the system user throughout some file found in the jenkins installed file location.
